name: Build gui.cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: UCRT64
        install: >-
          mingw-w64-ucrt-x86_64-gcc

    - name: Compile gui.cpp
      shell: msys2 {0}
      run: |
        g++ gui.cpp -o temperature.exe -mwindows -std=c++20

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: temperature.exe
        path: temperature.exe
